const state = { items: [] };
const $ = (selector) => document.querySelector(selector);
function classify(url) { const path = new URL(url).pathname.toLowerCase(); if (/\.(m3u8|mpd)$/.test(path)) return 'stream'; if (/\.(png|jpe?g|gif|webp|avif|svg|ico|bmp|tiff?)$/.test(path)) return 'image'; if (/\.(mp4|webm|mov|m4v|ogv)$/.test(path)) return 'video'; if (/\.(mp3|wav|ogg|m4a|aac|flac)$/.test(path)) return 'audio'; return 'other'; }
function updateCount() { const selected = state.items.filter((item) => item.selected).length; $('#count').textContent = `${selected} of ${state.items.length} selected`; $('#download').disabled = selected === 0; }
function render() { const query = $('#search').value.trim().toLowerCase(); const type = $('#type').value; const visible = state.items.filter((item) => (type === 'all' || item.type === type) && (!query || `${item.type} ${item.url}`.toLowerCase().includes(query))); $('#results').replaceChildren(...visible.map((item) => { const li = document.createElement('li'); const box = Object.assign(document.createElement('input'), { type: 'checkbox', checked: item.selected }); box.addEventListener('change', () => { item.selected = box.checked; updateCount(); }); li.append(box, Object.assign(document.createElement('span'), { className: 'kind', textContent: item.type }), Object.assign(document.createElement('a'), { className: 'url', textContent: item.url, href: item.url, target: '_blank', rel: 'noreferrer' })); return li; })); updateCount(); }
async function scanPage() { $('#status').textContent = 'Scanning...'; const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); const [{ result }] = await chrome.scripting.executeScript({ target: { tabId: tab.id }, func: () => { const found = new Set(); const add = (value) => { try { if (value && !value.startsWith('data:') && !value.startsWith('blob:')) found.add(new URL(value, document.baseURI).href); } catch {} }; document.querySelectorAll('img, video, audio, source').forEach((el) => { add(el.currentSrc); add(el.src); add(el.poster); (el.srcset || '').split(',').forEach((candidate) => add(candidate.trim().split(/\s+/)[0])); }); document.querySelectorAll('a[href]').forEach((el) => add(el.href)); document.querySelectorAll('*').forEach((el) => { for (const match of getComputedStyle(el).backgroundImage.matchAll(/url\(["']?(.*?)["']?\)/g)) add(match[1]); }); performance.getEntriesByType('resource').forEach((entry) => add(entry.name)); return [...found]; }}); state.items = result.map((url) => ({ url, type: classify(url), selected: true })); $('#status').textContent = state.items.length ? 'Review the assets found on this page.' : 'No media assets found.'; render(); }
function safeName(url, index) { const parsed = new URL(url); const raw = decodeURIComponent(parsed.pathname.split('/').pop() || `asset-${index + 1}`); return `${String(index + 1).padStart(3, '0')}-${raw.replace(/[^a-z0-9._-]+/gi, '_').slice(-140)}`; }
async function downloadZip() { const chosen = state.items.filter((item) => item.selected); const zip = new JSZip(); const errors = []; $('#download').disabled = true; for (const [index, item] of chosen.entries()) { $('#status').textContent = `Downloading ${index + 1} of ${chosen.length}...`; try { const response = await fetch(item.url); if (!response.ok) throw new Error(`${response.status}`); zip.file(safeName(item.url, index), await response.blob()); } catch (error) { errors.push(`${item.url}\t${error.message}`); } } zip.file('media-links.txt', chosen.map((item) => item.url).join('\n')); if (errors.length) zip.file('download-errors.txt', errors.join('\n')); const objectUrl = URL.createObjectURL(await zip.generateAsync({ type: 'blob' })); await chrome.downloads.download({ url: objectUrl, filename: `media-link-extractor-${Date.now()}.zip`, saveAs: true }); setTimeout(() => URL.revokeObjectURL(objectUrl), 60000); $('#status').textContent = errors.length ? `ZIP ready. ${errors.length} asset(s) could not be fetched.` : 'ZIP ready.'; updateCount(); }
$('#scan').addEventListener('click', () => scanPage().catch((error) => { $('#status').textContent = `Could not scan this page: ${error.message}`; })); $('#search').addEventListener('input', render); $('#type').addEventListener('change', render); $('#select-all').addEventListener('change', (event) => { state.items.forEach((item) => { item.selected = event.target.checked; }); render(); }); $('#download').addEventListener('click', () => downloadZip().catch((error) => { $('#status').textContent = `Could not create ZIP: ${error.message}`; updateCount(); }));
